services:
  - type: web
    name: finance-bot
    env: python
    repo: https://github.com/artemsharonov-cyber/newfinance_bot
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    pythonVersion: "3.11"  # Добавляем эту строку
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: finance-db
          property: connectionString
databases:
  - name: finance-db
    databaseName: finance_db
    plan: free
